spring:
  config:
    import: file:.env[.properties]
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/band_up_db
    username: admin
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
  liquibase:
    enabled: true
    change-log: classpath:/db/db.changelog-master.yaml
  security:
    jwt:
      secret: ${JWT_SECRET}
      tokenExpirationTimeInMinutes: 10000
      securityFilterPath: /api/auth/**

app:
  firebase:
    bucket: ${FIREBASE_CLOUD_STORAGE_BUCKET}